# Generated by Django 4.1.13 on 2024-01-29 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_booking', '0002_remove_booking_seat_categories_booking_seat_numbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_cost',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.ManyToManyField(to='movies_booking.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_booking.theater'),
        ),
    ]
