# Generated by Django 4.1.13 on 2024-01-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_booking', '0003_rename_total_cost_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='movie_date_time',
            new_name='booking_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='selected_seats',
            new_name='seats',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_numbers',
        ),
    ]
